# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logLikFunctionCpp <- function(params, categories, X1, y, family, Z_list, weights) {
    .Call('_orderedReg_logLikFunctionCpp', PACKAGE = 'orderedReg', params, categories, X1, y, family, Z_list, weights)
}

hessApproxCpp <- function(fun, x, delta = 1e-8) {
    .Call('_orderedReg_hessApproxCpp', PACKAGE = 'orderedReg', fun, x, delta)
}

gradApproxCpp <- function(fun, x, delta = 1e-8) {
    .Call('_orderedReg_gradApproxCpp', PACKAGE = 'orderedReg', fun, x, delta)
}

