# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logLikFunctionCpp <- function(params, categories, X1, y, family, Z_list = NULL, weights_ = NULL) {
    .Call('_orderedReg_logLikFunctionCpp', PACKAGE = 'orderedReg', params, categories, X1, y, family, Z_list, weights_)
}

